export const countriesData = [
  {
    name: 'Afghanistan',
    capital: 'Kabul',
    languages: ['Pashto', 'Uzbek', 'Turkmen'],
    population: 27657145,
    flag: 'https://flagcdn.com/af.svg',
    currency: 'Afghan afghani',
  },
  {
    name: 'Åland Islands',
    capital: 'Mariehamn',
    languages: ['Swedish'],
    population: 28875,
    flag: 'https://flagcdn.com/ax.svg',
    currency: 'Euro',
  },
  {
    name: 'Albania',
    capital: 'Tirana',
    languages: ['Albanian'],
    population: 2886026,
    flag: 'https://flagcdn.com/al.svg',
    currency: 'Albanian lek',
  },
  {
    name: 'Algeria',
    capital: 'Algiers',
    languages: ['Arabic'],
    population: 40400000,
    flag: 'https://flagcdn.com/dz.svg',
    currency: 'Algerian dinar',
  },
  {
    name: 'American Samoa',
    capital: 'Pago Pago',
    languages: ['English', 'Samoan'],
    population: 57100,
    flag: 'https://flagcdn.com/as.svg',
    currency: 'United State Dollar',
  },
  {
    name: 'Andorra',
    capital: 'Andorra la Vella',
    languages: ['Catalan'],
    population: 78014,
    flag: 'https://flagcdn.com/an.svg',
    currency: 'Euro',
  },
  {
    name: 'Angola',
    capital: 'Luanda',
    languages: ['Portuguese'],
    population: 25868000,
    flag: 'https://flagcdn.com/ao.svg',
    currency: 'Angolan kwanza',
  },
  {
    name: 'Anguilla',
    capital: 'The Valley',
    languages: ['English'],
    population: 13452,
    flag: 'https://flagcdn.com/ai.svg',
    currency: 'East Caribbean dollar',
  },
  {
    name: 'Antarctica',
    capital: '',
    languages: ['English', 'Russian'],
    population: 1000,
    flag: 'https://flagcdn.com/at.svg',
    currency: 'Australian dollar',
  },
  {
    name: 'Antigua and Barbuda',
    capital: "Saint John's",
    languages: ['English'],
    population: 86295,
    flag: 'https://flagcdn.com/ag.svg',
    currency: 'East Caribbean dollar',
  },
  {
    name: 'Argentina',
    capital: 'Buenos Aires',
    languages: ['Spanish', 'Guaraní'],
    population: 43590400,
    flag: 'https://flagcdn.com/ar.svg',
    currency: 'Argentine peso',
  },
  {
    name: 'Armenia',
    capital: 'Yerevan',
    languages: ['Armenian', 'Russian'],
    population: 2994400,
    flag: 'https://flagcdn.com/am.svg',
    currency: 'Armenian dram',
  },
  {
    name: 'Aruba',
    capital: 'Oranjestad',
    languages: ['Dutch', '(Eastern) Punjabi'],
    population: 107394,
    flag: 'https://flagcdn.com/aw.svg',
    currency: 'Aruban florin',
  },
  {
    name: 'Australia',
    capital: 'Canberra',
    languages: ['English'],
    population: 24117360,
    flag: 'https://flagcdn.com/au.svg',
    currency: 'Australian dollar',
  },
  {
    name: 'Austria',
    capital: 'Vienna',
    languages: ['German'],
    population: 8725931,
    flag: 'https://flagcdn.com/at.svg',
    currency: 'Euro',
  },
  {
    name: 'Azerbaijan',
    capital: 'Baku',
    languages: ['Azerbaijani'],
    population: 9730500,
    flag: 'https://flagcdn.com/az.svg',
    currency: 'Azerbaijani manat',
  },
  {
    name: 'Bahamas',
    capital: 'Nassau',
    languages: ['English'],
    population: 378040,
    flag: 'https://flagcdn.com/bh.svg',
    currency: 'Bahamian dollar',
  },
  {
    name: 'Bahrain',
    capital: 'Manama',
    languages: ['Arabic'],
    population: 1404900,
    flag: 'https://flagcdn.com/br.svg',
    currency: 'Bahraini dinar',
  },
  {
    name: 'Bangladesh',
    capital: 'Dhaka',
    languages: ['Bengali'],
    population: 161006790,
    flag: 'https://flagcdn.com/bg.svg',
    currency: 'Bangladeshi taka',
  },
  {
    name: 'Barbados',
    capital: 'Bridgetown',
    languages: ['English'],
    population: 285000,
    flag: 'https://flagcdn.com/bb.svg',
    currency: 'Barbadian dollar',
  },
  {
    name: 'Belarus',
    capital: 'Minsk',
    languages: ['Belarusian', 'Russian'],
    population: 9498700,
    flag: 'https://flagcdn.com/by.svg',
    currency: 'New Belarusian ruble',
  },
  {
    name: 'Belgium',
    capital: 'Brussels',
    languages: ['Dutch', 'French', 'German'],
    population: 11319511,
    flag: 'https://flagcdn.com/be.svg',
    currency: 'Euro',
  },
  {
    name: 'Belize',
    capital: 'Belmopan',
    languages: ['English', 'Spanish'],
    population: 370300,
    flag: 'https://flagcdn.com/bz.svg',
    currency: 'Belize dollar',
  },
  {
    name: 'Benin',
    capital: 'Porto-Novo',
    languages: ['French'],
    population: 10653654,
    flag: 'https://flagcdn.com/bj.svg',
    currency: 'West African CFA franc',
  },
  {
    name: 'Bermuda',
    capital: 'Hamilton',
    languages: ['English'],
    population: 61954,
    flag: 'https://flagcdn.com/bm.svg',
    currency: 'Bermudian dollar',
  },
  {
    name: 'Bhutan',
    capital: 'Thimphu',
    languages: ['Dzongkha'],
    population: 775620,
    flag: 'https://flagcdn.com/bt.svg',
    currency: 'Bhutanese ngultrum',
  },
  {
    name: 'Bolivia (Plurinational State of)',
    capital: 'Sucre',
    languages: ['Spanish', 'Aymara', 'Quechua'],
    population: 10985059,
    flag: 'https://flagcdn.com/bo.svg',
    currency: 'Bolivian boliviano',
  },
  {
    name: 'Bonaire, Sint Eustatius and Saba',
    capital: 'Kralendijk',
    languages: ['Dutch'],
    population: 17408,
    flag: 'https://flagcdn.com/bq.svg',
    currency: 'United States dollar',
  },
  {
    name: 'Bosnia and Herzegovina',
    capital: 'Sarajevo',
    languages: ['Bosnian', 'Croatian', 'Serbian'],
    population: 3531159,
    flag: 'https://flagcdn.com/ba.svg',
    currency: 'Bosnia and Herzegovina convertible mark',
  },
  {
    name: 'Botswana',
    capital: 'Gaborone',
    languages: ['English', 'Tswana'],
    population: 2141206,
    flag: 'https://flagcdn.com/bw.svg',
    currency: 'Botswana pula',
  },
  {
    name: 'Bouvet Island',
    capital: '',
    languages: ['Norwegian', 'Norwegian Bokmål', 'Norwegian Nynorsk'],
    population: 0,
    flag: 'https://flagcdn.com/bv.svg',
    currency: 'Norwegian krone',
  },
  {
    name: 'Brazil',
    capital: 'Brasília',
    languages: ['Portuguese'],
    population: 206135893,
    flag: 'https://flagcdn.com/br.svg',
    currency: 'Brazilian real',
  },
  {
    name: 'British Indian Ocean Territory',
    capital: 'Diego Garcia',
    languages: ['English'],
    population: 3000,
    flag: 'https://flagcdn.com/io.svg',
    currency: 'United States dollar',
  },
  {
    name: 'United States Minor Outlying Islands',
    capital: '',
    languages: ['English'],
    population: 300,
    flag: 'https://flagcdn.com/umi.svg',
    currency: 'United States Dollar',
  },
  {
    name: 'Virgin Islands (British)',
    capital: 'Road Town',
    languages: ['English'],
    population: 28514,
    flag: 'https://flagcdn.com/vgb.svg',
    currency: '[D]',
  },
  {
    name: 'Virgin Islands (U.S.)',
    capital: 'Charlotte Amalie',
    languages: ['English'],
    population: 114743,
    flag: 'https://flagcdn.com/vir.svg',
    currency: 'United States dollar',
  },
  {
    name: 'Brunei Darussalam',
    capital: 'Bandar Seri Begawan',
    languages: ['Malay'],
    population: 411900,
    flag: 'https://flagcdn.com/bn.svg',
    currency: 'Brunei dollar',
  },
  {
    name: 'Bulgaria',
    capital: 'Sofia',
    languages: ['Bulgarian'],
    population: 7153784,
    flag: 'https://flagcdn.com/bg.svg',
    currency: 'Bulgarian lev',
  },
  {
    name: 'Burkina Faso',
    capital: 'Ouagadougou',
    languages: ['French', 'Fula'],
    population: 19034397,
    flag: 'https://flagcdn.com/bf.svg',
    currency: 'West African CFA franc',
  },
  {
    name: 'Burundi',
    capital: 'Bujumbura',
    languages: ['French', 'Kirundi'],
    population: 10114505,
    flag: 'https://flagcdn.com/bi.svg',
    currency: 'Burundian franc',
  },
  {
    name: 'Cambodia',
    capital: 'Phnom Penh',
    languages: ['Khmer'],
    population: 15626444,
    flag: 'https://flagcdn.com/kh.svg',
    currency: 'Cambodian riel',
  },
  {
    name: 'Cameroon',
    capital: 'Yaoundé',
    languages: ['English', 'French'],
    population: 22709892,
    flag: 'https://flagcdn.com/cm.svg',
    currency: 'Central African CFA franc',
  },
  {
    name: 'Canada',
    capital: 'Ottawa',
    languages: ['English', 'French'],
    population: 36155487,
    flag: 'https://flagcdn.com/ca.svg',
    currency: 'Canadian dollar',
  },
  {
    name: 'Cabo Verde',
    capital: 'Praia',
    languages: ['Portuguese'],
    population: 531239,
    flag: 'https://flagcdn.com/cv.svg',
    currency: 'Cape Verdean escudo',
  },
  {
    name: 'Cayman Islands',
    capital: 'George Town',
    languages: ['English'],
    population: 58238,
    flag: 'https://flagcdn.com/ky.svg',
    currency: 'Cayman Islands dollar',
  },
  {
    name: 'Central African Republic',
    capital: 'Bangui',
    languages: ['French', 'Sango'],
    population: 4998000,
    flag: 'https://flagcdn.com/cf.svg',
    currency: 'Central African CFA franc',
  },
  {
    name: 'Chad',
    capital: "N'Djamena",
    languages: ['French', 'Arabic'],
    population: 14497000,
    flag: 'https://flagcdn.com/td.svg',
    currency: 'Central African CFA franc',
  },
  {
    name: 'Chile',
    capital: 'Santiago',
    languages: ['Spanish'],
    population: 18191900,
    flag: 'https://flagcdn.com/cl.svg',
    currency: 'Chilean peso',
  },
  {
    name: 'China',
    capital: 'Beijing',
    languages: ['Chinese'],
    population: 1377422166,
    flag: 'https://flagcdn.com/cn.svg',
    currency: 'Chinese yuan',
  },
  {
    name: 'Christmas Island',
    capital: 'Flying Fish Cove',
    languages: ['English'],
    population: 2072,
    flag: 'https://flagcdn.com/cx.svg',
    currency: 'Australian dollar',
  },
  {
    name: 'Cocos (Keeling) Islands',
    capital: 'West Island',
    languages: ['English'],
    population: 550,
    flag: 'https://flagcdn.com/cc.svg',
    currency: 'Australian dollar',
  },
  {
    name: 'Colombia',
    capital: 'Bogotá',
    languages: ['Spanish'],
    population: 48759958,
    flag: 'https://flagcdn.com/co.svg',
    currency: 'Colombian peso',
  },
  {
    name: 'Comoros',
    capital: 'Moroni',
    languages: ['Arabic', 'French'],
    population: 806153,
    flag: 'https://flagcdn.com/km.svg',
    currency: 'Comorian franc',
  },
  {
    name: 'Congo',
    capital: 'Brazzaville',
    languages: ['French', 'Lingala'],
    population: 4741000,
    flag: 'https://flagcdn.com/cg.svg',
    currency: 'Central African CFA franc',
  },
  {
    name: 'Congo (Democratic Republic of the)',
    capital: 'Kinshasa',
    languages: ['French', 'Lingala', 'Kongo', 'Swahili', 'Luba-Katanga'],
    population: 85026000,
    flag: 'https://flagcdn.com/cd.svg',
    currency: 'Congolese franc',
  },
  {
    name: 'Cook Islands',
    capital: 'Avarua',
    languages: ['English'],
    population: 18100,
    flag: 'https://flagcdn.com/ck.svg',
    currency: 'New Zealand dollar',
  },
  {
    name: 'Costa Rica',
    capital: 'San José',
    languages: ['Spanish'],
    population: 4890379,
    flag: 'https://flagcdn.com/cr.svg',
    currency: 'Costa Rican colón',
  },
  {
    name: 'Croatia',
    capital: 'Zagreb',
    languages: ['Croatian'],
    population: 4190669,
    flag: 'https://flagcdn.com/hr.svg',
    currency: 'Croatian kuna',
  },
  {
    name: 'Cuba',
    capital: 'Havana',
    languages: ['Spanish'],
    population: 11239004,
    flag: 'https://flagcdn.com/cu.svg',
    currency: 'Cuban convertible peso',
  },
  {
    name: 'Curaçao',
    capital: 'Willemstad',
    languages: ['Dutch', '(Eastern) Punjabi', 'English'],
    population: 154843,
    flag: 'https://flagcdn.com/cw.svg',
    currency: 'Netherlands Antillean guilder',
  },
  {
    name: 'Cyprus',
    capital: 'Nicosia',
    languages: ['Greek (modern)', 'Turkish', 'Armenian'],
    population: 847000,
    flag: 'https://flagcdn.com/cy.svg',
    currency: 'Euro',
  },
  {
    name: 'Czech Republic',
    capital: 'Prague',
    languages: ['Czech', 'Slovak'],
    population: 10558524,
    flag: 'https://flagcdn.com/cz.svg',
    currency: 'Czech koruna',
  },
  {
    name: 'Denmark',
    capital: 'Copenhagen',
    languages: ['Danish'],
    population: 5717014,
    flag: 'https://flagcdn.com/dk.svg',
    currency: 'Danish krone',
  },
  {
    name: 'Djibouti',
    capital: 'Djibouti',
    languages: ['French', 'Arabic'],
    population: 900000,
    flag: 'https://flagcdn.com/dj.svg',
    currency: 'Djiboutian franc',
  },
  {
    name: 'Dominica',
    capital: 'Roseau',
    languages: ['English'],
    population: 71293,
    flag: 'https://flagcdn.com/dm.svg',
    currency: 'East Caribbean dollar',
  },
  {
    name: 'Dominican Republic',
    capital: 'Santo Domingo',
    languages: ['Spanish'],
    population: 10075045,
    flag: 'https://flagcdn.com/do.svg',
    currency: 'Dominican peso',
  },
  {
    name: 'Ecuador',
    capital: 'Quito',
    languages: ['Spanish'],
    population: 16545799,
    flag: 'https://flagcdn.com/ec.svg',
    currency: 'United States dollar',
  },
  {
    name: 'Egypt',
    capital: 'Cairo',
    languages: ['Arabic'],
    population: 91290000,
    flag: 'https://flagcdn.com/eg.svg',
    currency: 'Egyptian pound',
  },
  {
    name: 'El Salvador',
    capital: 'San Salvador',
    languages: ['Spanish'],
    population: 6520675,
    flag: 'https://flagcdn.com/sl.svg',
    currency: 'United States dollar',
  },
  {
    name: 'Equatorial Guinea',
    capital: 'Malabo',
    languages: ['Spanish', 'French'],
    population: 1222442,
    flag: 'https://flagcdn.com/gn.svg',
    currency: 'Central African CFA franc',
  },
  {
    name: 'Eritrea',
    capital: 'Asmara',
    languages: ['Tigrinya', 'Arabic', 'English'],
    population: 5352000,
    flag: 'https://flagcdn.com/er.svg',
    currency: 'Eritrean nakfa',
  },
  {
    name: 'Estonia',
    capital: 'Tallinn',
    languages: ['Estonian'],
    population: 1315944,
    flag: 'https://flagcdn.com/es.svg',
    currency: 'Euro',
  },
  {
    name: 'Ethiopia',
    capital: 'Addis Ababa',
    languages: ['Amharic'],
    population: 92206005,
    flag: 'https://flagcdn.com/et.svg',
    currency: 'Ethiopian birr',
  },
  {
    name: 'Falkland Islands (Malvinas)',
    capital: 'Stanley',
    languages: ['English'],
    population: 2563,
    flag: 'https://flagcdn.com/fl.svg',
    currency: 'Falkland Islands pound',
  },
  {
    name: 'Faroe Islands',
    capital: 'Tórshavn',
    languages: ['Faroese'],
    population: 49376,
    flag: 'https://flagcdn.com/fr.svg',
    currency: 'Danish krone',
  },
  {
    name: 'Fiji',
    capital: 'Suva',
    languages: ['English', 'Fijian', 'Hindi', 'Urdu'],
    population: 867000,
    flag: 'https://flagcdn.com/fj.svg',
    currency: 'Fijian dollar',
  },
  {
    name: 'Finland',
    capital: 'Helsinki',
    languages: ['Finnish', 'Swedish'],
    population: 5491817,
    flag: 'https://flagcdn.com/fi.svg',
    currency: 'Euro',
  },
  {
    name: 'France',
    capital: 'Paris',
    languages: ['French'],
    population: 66710000,
    flag: 'https://flagcdn.com/fr.svg',
    currency: 'Euro',
  },
  {
    name: 'French Guiana',
    capital: 'Cayenne',
    languages: ['French'],
    population: 254541,
    flag: 'https://flagcdn.com/gu.svg',
    currency: 'Euro',
  },
  {
    name: 'French Polynesia',
    capital: 'Papeetē',
    languages: ['French'],
    population: 271800,
    flag: 'https://flagcdn.com/py.svg',
    currency: 'CFP franc',
  },
  {
    name: 'French Southern Territories',
    capital: 'Port-aux-Français',
    languages: ['French'],
    population: 140,
    flag: 'https://flagcdn.com/at.svg',
    currency: 'Euro',
  },
  {
    name: 'Gabon',
    capital: 'Libreville',
    languages: ['French'],
    population: 1802278,
    flag: 'https://flagcdn.com/ga.svg',
    currency: 'Central African CFA franc',
  },
  {
    name: 'Gambia',
    capital: 'Banjul',
    languages: ['English'],
    population: 1882450,
    flag: 'https://flagcdn.com/gm.svg',
    currency: 'Gambian dalasi',
  },
  {
    name: 'Georgia',
    capital: 'Tbilisi',
    languages: ['Georgian'],
    population: 3720400,
    flag: 'https://flagcdn.com/ge.svg',
    currency: 'Georgian Lari',
  },
  {
    name: 'Germany',
    capital: 'Berlin',
    languages: ['German'],
    population: 81770900,
    flag: 'https://flagcdn.com/de.svg',
    currency: 'Euro',
  },
  {
    name: 'Ghana',
    capital: 'Accra',
    languages: ['English'],
    population: 27670174,
    flag: 'https://flagcdn.com/gh.svg',
    currency: 'Ghanaian cedi',
  },
  {
    name: 'Gibraltar',
    capital: 'Gibraltar',
    languages: ['English'],
    population: 33140,
    flag: 'https://flagcdn.com/gi.svg',
    currency: 'Gibraltar pound',
  },
  {
    name: 'Greece',
    capital: 'Athens',
    languages: ['Greek (modern)'],
    population: 10858018,
    flag: 'https://flagcdn.com/gr.svg',
    currency: 'Euro',
  },
  {
    name: 'Greenland',
    capital: 'Nuuk',
    languages: ['Kalaallisut'],
    population: 55847,
    flag: 'https://flagcdn.com/gr.svg',
    currency: 'Danish krone',
  },
  {
    name: 'Grenada',
    capital: "St. George's",
    languages: ['English'],
    population: 103328,
    flag: 'https://flagcdn.com/gr.svg',
    currency: 'East Caribbean dollar',
  },
  {
    name: 'Guadeloupe',
    capital: 'Basse-Terre',
    languages: ['French'],
    population: 400132,
    flag: 'https://flagcdn.com/gp.svg',
    currency: 'Euro',
  },
  {
    name: 'Guam',
    capital: 'Hagåtña',
    languages: ['English', 'Chamorro', 'Spanish'],
    population: 184200,
    flag: 'https://flagcdn.com/gm.svg',
    currency: 'United States dollar',
  },
  {
    name: 'Guatemala',
    capital: 'Guatemala City',
    languages: ['Spanish'],
    population: 16176133,
    flag: 'https://flagcdn.com/gm.svg',
    currency: 'Guatemalan quetzal',
  },
  {
    name: 'Guernsey',
    capital: 'St. Peter Port',
    languages: ['English', 'French'],
    population: 62999,
    flag: 'https://flagcdn.com/gy.svg',
    currency: 'British pound',
  },
  {
    name: 'Guinea',
    capital: 'Conakry',
    languages: ['French', 'Fula'],
    population: 12947000,
    flag: 'https://flagcdn.com/gn.svg',
    currency: 'Guinean franc',
  },
  {
    name: 'Guinea-Bissau',
    capital: 'Bissau',
    languages: ['Portuguese'],
    population: 1547777,
    flag: 'https://flagcdn.com/gb.svg',
    currency: 'West African CFA franc',
  },
  {
    name: 'Guyana',
    capital: 'Georgetown',
    languages: ['English'],
    population: 746900,
    flag: 'https://flagcdn.com/gy.svg',
    currency: 'Guyanese dollar',
  },
  {
    name: 'Haiti',
    capital: 'Port-au-Prince',
    languages: ['French', 'Haitian'],
    population: 11078033,
    flag: 'https://flagcdn.com/hi.svg',
    currency: 'Haitian gourde',
  },
  {
    name: 'Heard Island and McDonald Islands',
    capital: '',
    languages: ['English'],
    population: 0,
    flag: 'https://flagcdn.com/hd.svg',
    currency: 'Australian dollar',
  },
  {
    name: 'Holy See',
    capital: 'Rome',
    languages: ['Latin', 'Italian', 'French', 'German'],
    population: 451,
    flag: 'https://flagcdn.com/vt.svg',
    currency: 'Euro',
  },
  {
    name: 'Honduras',
    capital: 'Tegucigalpa',
    languages: ['Spanish'],
    population: 8576532,
    flag: 'https://flagcdn.com/hd.svg',
    currency: 'Honduran lempira',
  },
  {
    name: 'Hong Kong',
    capital: 'City of Victoria',
    languages: ['English', 'Chinese'],
    population: 7324300,
    flag: 'https://flagcdn.com/hg.svg',
    currency: 'Hong Kong dollar',
  },
  {
    name: 'Hungary',
    capital: 'Budapest',
    languages: ['Hungarian'],
    population: 9823000,
    flag: 'https://flagcdn.com/hn.svg',
    currency: 'Hungarian forint',
  },
  {
    name: 'Iceland',
    capital: 'Reykjavík',
    languages: ['Icelandic'],
    population: 334300,
    flag: 'https://flagcdn.com/il.svg',
    currency: 'Icelandic króna',
  },
  {
    name: 'India',
    capital: 'New Delhi',
    languages: ['Hindi', 'English'],
    population: 1295210000,
    flag: 'https://flagcdn.com/id.svg',
    currency: 'Indian rupee',
  },
  {
    name: 'Indonesia',
    capital: 'Jakarta',
    languages: ['Indonesian'],
    population: 258705000,
    flag: 'https://flagcdn.com/in.svg',
    currency: 'Indonesian rupiah',
  },
  {
    name: "Côte d'Ivoire",
    capital: 'Yamoussoukro',
    languages: ['French'],
    population: 22671331,
    flag: 'https://flagcdn.com/cv.svg',
    currency: 'West African CFA franc',
  },
  {
    name: 'Iran (Islamic Republic of)',
    capital: 'Tehran',
    languages: ['Persian (Farsi)'],
    population: 79369900,
    flag: 'https://flagcdn.com/in.svg',
    currency: 'Iranian rial',
  },
  {
    name: 'Iraq',
    capital: 'Baghdad',
    languages: ['Arabic', 'Kurdish'],
    population: 37883543,
    flag: 'https://flagcdn.com/iq.svg',
    currency: 'Iraqi dinar',
  },
  {
    name: 'Ireland',
    capital: 'Dublin',
    languages: ['Irish', 'English'],
    population: 6378000,
    flag: 'https://flagcdn.com/il.svg',
    currency: 'Euro',
  },
  {
    name: 'Isle of Man',
    capital: 'Douglas',
    languages: ['English', 'Manx'],
    population: 84497,
    flag: 'https://flagcdn.com/in.svg',
    currency: 'British pound',
  },
  {
    name: 'Israel',
    capital: 'Jerusalem',
    languages: ['Hebrew (modern)', 'Arabic'],
    population: 8527400,
    flag: 'https://flagcdn.com/ir.svg',
    currency: 'Israeli new shekel',
  },
  {
    name: 'Italy',
    capital: 'Rome',
    languages: ['Italian'],
    population: 60665551,
    flag: 'https://flagcdn.com/ia.svg',
    currency: 'Euro',
  },
  {
    name: 'Jamaica',
    capital: 'Kingston',
    languages: ['English'],
    population: 2723246,
    flag: 'https://flagcdn.com/jm.svg',
    currency: 'Jamaican dollar',
  },
  {
    name: 'Japan',
    capital: 'Tokyo',
    languages: ['Japanese'],
    population: 126960000,
    flag: 'https://flagcdn.com/jp.svg',
    currency: 'Japanese yen',
  },
  {
    name: 'Jersey',
    capital: 'Saint Helier',
    languages: ['English', 'French'],
    population: 100800,
    flag: 'https://flagcdn.com/je.svg',
    currency: 'British pound',
  },
  {
    name: 'Jordan',
    capital: 'Amman',
    languages: ['Arabic'],
    population: 9531712,
    flag: 'https://flagcdn.com/jo.svg',
    currency: 'Jordanian dinar',
  },
  {
    name: 'Kazakhstan',
    capital: 'Astana',
    languages: ['Kazakh', 'Russian'],
    population: 17753200,
    flag: 'https://flagcdn.com/ka.svg',
    currency: 'Kazakhstani tenge',
  },
  {
    name: 'Kenya',
    capital: 'Nairobi',
    languages: ['English', 'Swahili'],
    population: 47251000,
    flag: 'https://flagcdn.com/ke.svg',
    currency: 'Kenyan shilling',
  },
  {
    name: 'Kiribati',
    capital: 'South Tarawa',
    languages: ['English'],
    population: 113400,
    flag: 'https://flagcdn.com/ki.svg',
    currency: 'Australian dollar',
  },
  {
    name: 'Kuwait',
    capital: 'Kuwait City',
    languages: ['Arabic'],
    population: 4183658,
    flag: 'https://flagcdn.com/kw.svg',
    currency: 'Kuwaiti dinar',
  },
  {
    name: 'Kyrgyzstan',
    capital: 'Bishkek',
    languages: ['Kyrgyz', 'Russian'],
    population: 6047800,
    flag: 'https://flagcdn.com/kg.svg',
    currency: 'Kyrgyzstani som',
  },
  {
    name: "Lao People's Democratic Republic",
    capital: 'Vientiane',
    languages: ['Lao'],
    population: 6492400,
    flag: 'https://flagcdn.com/la.svg',
    currency: 'Lao kip',
  },
  {
    name: 'Latvia',
    capital: 'Riga',
    languages: ['Latvian'],
    population: 1961600,
    flag: 'https://flagcdn.com/lv.svg',
    currency: 'Euro',
  },
  {
    name: 'Lebanon',
    capital: 'Beirut',
    languages: ['Arabic', 'French'],
    population: 5988000,
    flag: 'https://flagcdn.com/lb.svg',
    currency: 'Lebanese pound',
  },
  {
    name: 'Lesotho',
    capital: 'Maseru',
    languages: ['English', 'Southern Sotho'],
    population: 1894194,
    flag: 'https://flagcdn.com/l.svg',
    currency: 'Lesotho loti',
  },
  {
    name: 'Liberia',
    capital: 'Monrovia',
    languages: ['English'],
    population: 4615000,
    flag: 'https://flagcdn.com/lr.svg',
    currency: 'Liberian dollar',
  },
  {
    name: 'Libya',
    capital: 'Tripoli',
    languages: ['Arabic'],
    population: 6385000,
    flag: 'https://flagcdn.com/ly.svg',
    currency: 'Libyan dinar',
  },
  {
    name: 'Liechtenstein',
    capital: 'Vaduz',
    languages: ['German'],
    population: 37623,
    flag: 'https://flagcdn.com/le.svg',
    currency: 'Swiss franc',
  },
  {
    name: 'Lithuania',
    capital: 'Vilnius',
    languages: ['Lithuanian'],
    population: 2872294,
    flag: 'https://flagcdn.com/lu.svg',
    currency: 'Euro',
  },
  {
    name: 'Luxembourg',
    capital: 'Luxembourg',
    languages: ['French', 'German', 'Luxembourgish'],
    population: 576200,
    flag: 'https://flagcdn.com/lx.svg',
    currency: 'Euro',
  },
  {
    name: 'Macao',
    capital: '',
    languages: ['Chinese', 'Portuguese'],
    population: 649100,
    flag: 'https://flagcdn.com/mc.svg',
    currency: 'Macanese pataca',
  },
  {
    name: 'Macedonia (the former Yugoslav Republic of)',
    capital: 'Skopje',
    languages: ['Macedonian'],
    population: 2058539,
    flag: 'https://flagcdn.com/md.svg',
    currency: 'Macedonian denar',
  },
  {
    name: 'Madagascar',
    capital: 'Antananarivo',
    languages: ['French', 'Malagasy'],
    population: 22434363,
    flag: 'https://flagcdn.com/mg.svg',
    currency: 'Malagasy ariary',
  },
  {
    name: 'Malawi',
    capital: 'Lilongwe',
    languages: ['English', 'Chichewa'],
    population: 16832910,
    flag: 'https://flagcdn.com/mi.svg',
    currency: 'Malawian kwacha',
  },
  {
    name: 'Malaysia',
    capital: 'Kuala Lumpur',
    languages: ['Malaysian'],
    population: 31405416,
    flag: 'https://flagcdn.com/ms.svg',
    currency: 'Malaysian ringgit',
  },
  {
    name: 'Maldives',
    capital: 'Malé',
    languages: ['Divehi'],
    population: 344023,
    flag: 'https://flagcdn.com/mv.svg',
    currency: 'Maldivian rufiyaa',
  },
  {
    name: 'Mali',
    capital: 'Bamako',
    languages: ['French'],
    population: 18135000,
    flag: 'https://flagcdn.com/ml.svg',
    currency: 'West African CFA franc',
  }
]
